import { describe, it, expect } from 'vitest';
import { createAITagger } from './ai-tags.js';

describe('AI Tagging', () => {
  const tagger = createAITagger();

  describe('explicit level', () => {
    it('should classify trailers as explicit', () => {
      const cases = [
        'feat: new feature\n\nAI: true',
        'feat: new feature\n\nX-AI: true',
        'feat: new feature\n\nCo-authored-by: Claude <noreply@anthropic.com>',
        'feat: new feature\n\nCo-authored-by: copilot[bot] <copilot@github.com>',
        'feat: new feature\n\nCo-authored-by: ChatGPT <noreply@openai.com>',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(true);
        expect(result.level).toBe('explicit');
      });
    });

    it('should classify [AI] tag as explicit', () => {
      const result = tagger('[AI] automated code generation');
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
      expect(result.sources).toContain('tag:[ai]');
    });

    it('should classify creation verb + tool as explicit', () => {
      const cases = [
        'feat: generated by copilot',
        'feat: created with claude',
        'feat: written using chatgpt',
        'feat: built with gemini',
        'feat: cursor generated the auth module',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(true);
        expect(result.level).toBe('explicit');
      });
    });

    it('should classify Claude Code commits as explicit', () => {
      const claudeCommit = `fix: resolve authentication bug

Generated with Claude Code
Co-Authored-By: Claude <noreply@anthropic.com>`;

      const result = tagger(claudeCommit);
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
    });
  });

  describe('implicit level', () => {
    it('should classify suggestion/help verbs + tool as implicit', () => {
      const cases = [
        'fix: copilot suggestions',
        'feat: chatgpt assisted refactoring',
        'feat: with help from claude',
        'fix: reviewed by gemini',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(true);
        expect(result.level).toBe('implicit');
      });
    });
  });

  describe('mention level', () => {
    it('should classify negative context + tool as mention (ai: false)', () => {
      const cases = [
        'fix: copilot bug in autocomplete',
        'chore: add cursor support',
        'chore: configure windsurf settings',
        'chore: update claude integration',
        'docs: document copilot setup',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(false);
        expect(result.level).toBe('mention');
      });
    });

    it('should classify bare tool name as mention (ai: false)', () => {
      const cases = [
        'feat: copilot improvements',
        'chore: cursor config changes',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(false);
        expect(result.level).toBe('mention');
      });
    });
  });

  describe('none level', () => {
    it('should classify messages without AI references as none', () => {
      const cases = [
        'regular commit message',
        'feat: add user authentication',
        'fix: resolve memory leak in parser',
        'chore: add AI attribution manifest',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(false);
        expect(result.level).toBe('none');
      });
    });
  });

  describe('edge cases', () => {
    it('should not match human Co-authored-by', () => {
      const result = tagger('feat: new feature\n\nCo-authored-by: John <john@example.com>');
      expect(result.ai).toBe(false);
      expect(result.level).toBe('none');
    });

    it('should handle custom patterns as explicit', () => {
      const customTagger = createAITagger({ patterns: ['custom-ai-tool'] });
      const result = customTagger('fix: custom-ai-tool generated code');
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
    });

    it('should prioritize explicit over mention context', () => {
      const result = tagger('fix: generated with claude');
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
    });
  });

  describe('bot blocklist', () => {
    it('should not classify non-AI bot trailers as AI', () => {
      const cases = [
        'chore(deps): bump lodash\n\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>',
        'chore(deps): update deps\n\nCo-authored-by: renovate[bot] <renovate@whitesourcesoftware.com>',
        'ci: retry\n\nCo-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(false);
        expect(result.level).toBe('none');
      });
    });

    it('should still classify AI bot trailers as explicit', () => {
      const result = tagger(
        'feat: new feature\n\nCo-authored-by: copilot[bot] <copilot@github.com>'
      );
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
    });

    it('should support extending the blocklist via config', () => {
      const customTagger = createAITagger({ patterns: [], botBlocklist: ['acme-bot'] });
      const result = customTagger(
        'chore: automated\n\nCo-authored-by: acme-bot <bot@github.com>'
      );
      expect(result.ai).toBe(false);
      expect(result.level).toBe('none');
    });

    it('should still detect a real AI co-author alongside a blocklisted bot', () => {
      const result = tagger(
        `feat: thing

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Claude <noreply@anthropic.com>`
      );
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
    });
  });

  describe('configurable tools', () => {
    it('should detect custom tool names across all levels', () => {
      const customTagger = createAITagger({ patterns: [], tools: ['devbot'] });

      expect(customTagger('feat: generated by devbot').level).toBe('explicit');
      expect(customTagger('feat: devbot suggestions').level).toBe('implicit');
      expect(customTagger('fix: devbot bug').level).toBe('mention');
      expect(customTagger('feat: devbot improvements').level).toBe('mention');
      expect(customTagger('regular commit').level).toBe('none');
    });

    it('should still detect default tools when custom tools are added', () => {
      const customTagger = createAITagger({ patterns: [], tools: ['devbot'] });

      expect(customTagger('feat: generated by copilot').level).toBe('explicit');
      expect(customTagger('feat: copilot suggestions').level).toBe('implicit');
    });

    it('should detect custom trailer domains', () => {
      const customTagger = createAITagger({ patterns: [], trailerDomains: ['mycompany\\.com'] });

      const result = customTagger('feat: new feature\n\nCo-authored-by: Bot <bot@mycompany.com>');
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
    });
  });

  describe('autonomy mode inference', () => {
    it('infers agent from Claude Code and the Claude trailer convention', () => {
      const result = tagger(
        'fix: bug\n\nGenerated with Claude Code\nCo-Authored-By: Claude <noreply@anthropic.com>'
      );
      expect(result.mode).toBe('agent');
      expect(result.modeEvidence).toBe('inferred');
    });

    it('infers autocomplete from copilot and assisted from IDE tools', () => {
      expect(tagger('feat: generated by copilot').mode).toBe('autocomplete');
      expect(tagger('feat: generated by cursor').mode).toBe('assisted');
      expect(tagger('feat: written using chatgpt').mode).toBe('assisted');
    });

    it('leaves mode unknown with no evidence for anonymous AI signals', () => {
      const result = tagger('[AI] automated change');
      expect(result.ai).toBe(true);
      expect(result.mode).toBe('unknown');
      expect(result.modeEvidence).toBe('none');
    });

    it('never infers a mode for non-AI commits', () => {
      const result = tagger('fix: update claude detection pattern'); // mention only
      expect(result.ai).toBe(false);
      expect(result.mode).toBe('unknown');
      expect(result.modeEvidence).toBe('none');
    });
  });

  describe('three-state attribution', () => {
    it('maps explicit and implicit levels to attribution: ai', () => {
      expect(tagger('[AI] automated change').attribution).toBe('ai');
      expect(tagger('feat: copilot suggestions applied').attribution).toBe('ai');
    });

    it('maps mention and none levels to attribution: unknown, never human', () => {
      expect(tagger('fix: update claude detection pattern').attribution).toBe('unknown');
      expect(tagger('regular commit with no AI signal').attribution).toBe('unknown');
    });
  });
});
