import { describe, it, expect } from 'vitest';
import { createAITagger } from './ai-tags.js';

describe('AI Tagging', () => {
  const tagger = createAITagger();

  describe('explicit level', () => {
    it('should classify trailers as explicit', () => {
      const cases = [
        'feat: new feature\n\nAI: true',
        'feat: new feature\n\nX-AI: true',
        'feat: new feature\n\nCo-authored-by: Claude <noreply@anthropic.com>',
        'feat: new feature\n\nCo-authored-by: copilot[bot] <copilot@github.com>',
        'feat: new feature\n\nCo-authored-by: ChatGPT <noreply@openai.com>',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(true);
        expect(result.level).toBe('explicit');
      });
    });

    it('should classify [AI] tag as explicit', () => {
      const result = tagger('[AI] automated code generation');
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
      expect(result.sources).toContain('tag:[ai]');
    });

    it('should classify creation verb + tool as explicit', () => {
      const cases = [
        'feat: generated by copilot',
        'feat: created with claude',
        'feat: written using chatgpt',
        'feat: built with gemini',
        'feat: cursor generated the auth module',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(true);
        expect(result.level).toBe('explicit');
      });
    });

    it('should classify Claude Code commits as explicit', () => {
      const claudeCommit = `fix: resolve authentication bug

Generated with Claude Code
Co-Authored-By: Claude <noreply@anthropic.com>`;

      const result = tagger(claudeCommit);
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
    });
  });

  describe('implicit level', () => {
    it('should classify suggestion/help verbs + tool as implicit', () => {
      const cases = [
        'fix: copilot suggestions',
        'feat: chatgpt assisted refactoring',
        'feat: with help from claude',
        'fix: reviewed by gemini',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(true);
        expect(result.level).toBe('implicit');
      });
    });
  });

  describe('mention level', () => {
    it('should classify negative context + tool as mention (ai: false)', () => {
      const cases = [
        'fix: copilot bug in autocomplete',
        'chore: add cursor support',
        'chore: configure windsurf settings',
        'chore: update claude integration',
        'docs: document copilot setup',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(false);
        expect(result.level).toBe('mention');
      });
    });

    it('should classify bare tool name as mention (ai: false)', () => {
      const cases = [
        'feat: copilot improvements',
        'chore: cursor config changes',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(false);
        expect(result.level).toBe('mention');
      });
    });
  });

  describe('none level', () => {
    it('should classify messages without AI references as none', () => {
      const cases = [
        'regular commit message',
        'feat: add user authentication',
        'fix: resolve memory leak in parser',
        'chore: add AI attribution manifest',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.ai).toBe(false);
        expect(result.level).toBe('none');
      });
    });
  });

  describe('edge cases', () => {
    it('should not match human Co-authored-by', () => {
      const result = tagger('feat: new feature\n\nCo-authored-by: John <john@example.com>');
      expect(result.ai).toBe(false);
      expect(result.level).toBe('none');
    });

    it('should handle custom patterns as explicit', () => {
      const customTagger = createAITagger({ patterns: ['custom-ai-tool'] });
      const result = customTagger('fix: custom-ai-tool generated code');
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
    });

    it('should prioritize explicit over mention context', () => {
      // "Generated with Claude" is explicit even though "fix" might suggest mention
      const result = tagger('fix: generated with claude');
      expect(result.ai).toBe(true);
      expect(result.level).toBe('explicit');
    });
  });
});
